path: /set/me/please/ # The path to the folder containing the datasets
lep_vars: px,py,eta,log_energy # Which lepton kinematic features to use as inputs, see /nureg/physics/change_cords for options
jet_vars: px,py,eta,log_energy # Which jet kinematic features to use as inputs
out_vars: px,py,eta # Which neutrino kinematic features to use as outputs/targets
scaler_nm: standard # Name of the preprosessing scalar see /nureg/utils/get_scaler
incl_quad: false # If the two components of the quadratic solutions should be included as inputs